[project]
name = "django-template"
version = "0.1.0"
description = "A powerful Django template for creating web applications."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ruff>=0.9.6",
]
